INSERT INTO CATEGORY (ID, CREATED, UPDATED, DESCRIPTION, NAME, PARENT_ID) VALUES (0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Top level category', 'Top Level', 0);
INSERT INTO CATEGORY (ID, CREATED, UPDATED, DESCRIPTION, NAME, PARENT_ID) VALUES (1001, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Какое-то описание категории', 'Ветеринария', 0);
INSERT INTO CATEGORY (ID, CREATED, UPDATED, DESCRIPTION, NAME, PARENT_ID) VALUES (1002, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Какое-то описание категории', 'Антибактериальные препараты', 1001);

INSERT INTO ITEM (ID, CREATED, UPDATED, NAME, PRICE) VALUES (2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Максус G100', 2500);
INSERT INTO ITEM (ID, CREATED, UPDATED, NAME, PRICE) VALUES (2001, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Максус G100', 2500);
INSERT INTO ITEM (ID, CREATED, UPDATED, NAME, PRICE) VALUES (2002, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Максус G100', 2500);
INSERT INTO ITEM (ID, CREATED, UPDATED, NAME, PRICE) VALUES (2003, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Максус G100', 2500);
INSERT INTO ITEM (ID, CREATED, UPDATED, NAME, PRICE) VALUES (2004, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Максус G100', 2500);

INSERT INTO CATEGORY_ITEM_RELATIONSHIP (CATEGORY_ID, ITEM_ID, DATEADDED) VALUES (1002, 2000, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY_ITEM_RELATIONSHIP (CATEGORY_ID, ITEM_ID, DATEADDED) VALUES (1002, 2001, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY_ITEM_RELATIONSHIP (CATEGORY_ID, ITEM_ID, DATEADDED) VALUES (1002, 2002, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY_ITEM_RELATIONSHIP (CATEGORY_ID, ITEM_ID, DATEADDED) VALUES (1002, 2003, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY_ITEM_RELATIONSHIP (CATEGORY_ID, ITEM_ID, DATEADDED) VALUES (1002, 2004, CURRENT_TIMESTAMP);

INSERT INTO SELLER (ID, CREATED, UPDATED, ADDRESS, EMAIL, NAME) VALUES (1001, CURRENT_TIMESTAMP, null, 'Dummy Address', 'Dummy@dummymail.com', 'Dummy name');
